language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install awscli
  - aws s3 sync public/ s3://marioharvey.com --delete --storage-class REDUCED_REDUNDANCY
notifications:
    email:
        on_failure: always