---
  AWSTemplateFormatVersion: 2010-09-09
  Description: setup domain and s3 bucket for marioharvey.com
  Parameters:
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances
      Default: 1
  Resources:
    DNS: 
      Type: AWS::Route53::HostedZone
      Properties: 
        HostedZoneConfig: 
          Comment: My hosted zone for blog marioharvey.com
        Name: marioharvey.com
    S3Bucket: 
      Type: AWS::S3::Bucket
      Properties: 
        AccessControl: PublicRead
        BucketName: marioharvey.com
        WebsiteConfiguration: 
          IndexDocument: index.html
          ErrorDocument: 404.html
    #create rewrite rules for bucket
    #create cloudfront distro
    #setup cloudfront distro to point at website endpoint
    #add route53 records to point to cloudfront distro
